[context.production.environment]
  ACC_API = "https://accapi.appbase.io"
  SCALR_API = "https://scalr.api.appbase.io"

[context.deploy-preview.environment]
  ACC_API = "https://accapi-staging.reactiveapps.io"
  SCALR_API = "https://api-staging.reactiveapps.io"

[context.branch-deploy.environment]
  ACC_API = "https://accapi.appbase.io"
  SCALR_API = "https://scalr.api.appbase.io"
